### ISSUE TITLE
Not Running on Latest Version of Numpy and Scipy

### ISSUE THREAD

**Issue by pranavsinghpatil** [The-Independent-Code/Neural-Network#6]
UserWarning: A NumPy version >=1.21.6 and <1.28.0 is required for this version of SciPy (detected version 2.0.2)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

**Comment by omaraflak** [comment]
That's due to your environment. Just create a virtual env and `pip install numpy scipy`.
